In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_excel(r"C:\Users\sonim\Desktop\CUSTOMER SEGMENTATION\DATA\RAW\online_retail_II.xlsx")

In [ ]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [ ]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [ ]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [ ]:
df.shape

(525461, 8)

In [ ]:
df=df.dropna(subset=["Customer ID"])

In [ ]:
df.shape

(417534, 8)

In [ ]:
df[df["Invoice"].astype(str).str.startswith("C")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [ ]:
cancelled = df["Invoice"].astype(str).str.startswith("C").sum()
print(cancelled)

9839

In [ ]:
df = df[~df["Invoice"].astype(str).str.startswith("C")]

In [ ]:
df.shape

(407695, 8)

In [ ]:
df.duplicated().sum()

np.int64(6748)

In [ ]:
duplicates = df[df.duplicated(keep=False)]
duplicates.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [ ]:
duplicates.sort_values(by=["Invoice", "StockCode"]).head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(400947, 8)

In [ ]:
df["TotalPrice"] = df["Quantity"] * df["Price"]

In [ ]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [ ]:
(df["Quantity"] <= 0).sum()

np.int64(0)

In [ ]:
(df["TotalPrice"] <= 0).sum()

np.int64(31)

In [ ]:
df[df["TotalPrice"] <= 0][["Invoice", "StockCode", "Description", "Quantity", "Price", "TotalPrice"]]

,Invoice,StockCode,Description,Quantity,Price,TotalPrice
4674,489825,22076,6 RIBBONS EMPIRE,12,0.0,0.0
6781,489998,48185,DOOR MAT FAIRY CAKE,2,0.0,0.0
16107,490727,M,Manual,1,0.0,0.0
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,0.0,0.0
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,0.0,0.0
32916,492079,85042,ANTIQUE LILY FAIRY LIGHTS,8,0.0,0.0
40101,492760,21143,ANTIQUE GLASS HEART DECORATION,12,0.0,0.0
47126,493761,79320,FLAMINGO LIGHTS,24,0.0,0.0
48342,493899,22355,"CHARLOTTE BAG , SUKI DESIGN",10,0.0,0.0
57619,494607,21533,RETRO SPOT LARGE MILK JUG,12,0.0,0.0
89084,497819,TEST001,This is a test product.,5,0.0,0.0
89180,497843,TEST001,This is a test product.,5,0.0,0.0
111348,500073,21662,VINTAGE GLASS COFFEE CADDY,1,0.0,0.0
149201,503585,22459,CAST IRON HOOK GARDEN TROWEL,8,0.0,0.0
149202,503585,22458,CAST IRON HOOK GARDEN FORK,8,0.0,0.0
166143,505083,22376,AIRLINE BAG VINTAGE JET SET WHITE,1,0.0,0.0
232526,511902,21765,HANGING METAL BIRD BATH,1,0.0,0.0
240455,512609,20914,SET/5 RED SPOTTY LID GLASS BOWLS,2,0.0,0.0
248583,513416,22423,REGENCY CAKESTAND 3 TIER,5,0.0,0.0
276858,516304,22690,DOORMAT HOME SWEET HOME BLUE,6,0.0,0.0
296375,518231,22472,TV DINNER TRAY DOLLY GIRL,9,0.0,0.0
327801,521375,22202,MILK PAN PINK RETROSPOT,3,0.0,0.0
358820,524181,46000M,POLYESTER FILLER PAD 45x45cm,648,0.0,0.0
364333,524701,22218,CAKE STAND LACE WHITE,2,0.0,0.0
392008,527084,22630,DOLLY GIRL LUNCH BOX,64,0.0,0.0
400047,527696,22121,NOEL WOODEN BLOCK LETTERS,1,0.0,0.0
439309,531361,21843,RED RETROSPOT CAKE STAND,2,0.0,0.0
453705,532470,22624,IVORY KITCHEN SCALES,2,0.0,0.0
471775,533822,22846,BREAD BIN DINER STYLE RED,1,0.0,0.0
471776,533822,22845,VINTAGE CREAM CAT FOOD CONTAINER,1,0.0,0.0
512240,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,0.0

In [ ]:
df = df[df["TotalPrice"] > 0]

In [ ]:
df.shape

(400916, 9)

In [ ]:
(df["TotalPrice"] <= 0).sum()

np.int64(0)

In [ ]:
df.to_csv("C:\\Users\\sonim\\Desktop\\CUSTOMER SEGMENTATION\\DATA\\RAW\\processed_data.csv", index=False)